export const farmers = [
  {
    name: 'João',
    cpf: '123.456.789-00',
    surname: 'Silva',
    sex: 'Masculino',
    maritalStatus: 'Solteiro',
    creditLine: 'Boa',
    course: 'Engenharia',
    phone: '(11) 1234-5678',
    address: 'Rua A, 123',
  },
  {
    name: 'Maria',
    cpf: '987.654.321-00',
    surname: 'Santos',
    sex: 'Feminino',
    maritalStatus: 'Casada',
    creditLine: 'Regular',
    course: 'Medicina',
    phone: '(22) 5555-5555',
    address: 'Avenida B, 456',
  },
  {
    name: 'Carlos',
    cpf: '111.222.333-44',
    surname: 'Oliveira',
    sex: 'Masculino',
    maritalStatus: 'Solteiro',
    creditLine: 'Ótima',
    course: 'Administração',
    phone: '(33) 8888-8888',
    address: 'Rua X, 789',
  },
  {
    name: 'Ana',
    cpf: '555.666.777-88',
    surname: 'Pereira',
    sex: 'Feminino',
    maritalStatus: 'Viúva',
    creditLine: 'Boa',
    course: 'Psicologia',
    phone: '(44) 7777-7777',
    address: 'Av. Y, 654',
  },
  {
    name: 'Pedro',
    cpf: '999.000.111-22',
    surname: 'Ribeiro',
    sex: 'Masculino',
    maritalStatus: 'Casado',
    creditLine: 'Regular',
    course: 'Direito',
    phone: '(55) 6666-6666',
    address: 'Rua Z, 987',
  },
  {
    name: 'Mariana',
    cpf: '222.333.444-55',
    surname: 'Fernandes',
    sex: 'Feminino',
    maritalStatus: 'Divorciada',
    creditLine: 'Boa',
    course: 'Arquitetura',
    phone: '(66) 4444-4444',
    address: 'Av. C, 321',
  },
  {
    name: 'Luiz',
    cpf: '333.444.555-66',
    surname: 'Gomes',
    sex: 'Masculino',
    maritalStatus: 'Solteiro',
    creditLine: 'Ótima',
    course: 'Economia',
    phone: '(77) 3333-3333',
    address: 'Rua M, 456',
  },
  {
    name: 'Julia',
    cpf: '444.555.666-77',
    surname: 'Martins',
    sex: 'Feminino',
    maritalStatus: 'Casada',
    creditLine: 'Regular',
    course: 'Ciência da Computação',
    phone: '(88) 2222-2222',
    address: 'Av. P, 789',
  },
  {
    name: 'Lucas',
    cpf: '777.888.999-00',
    surname: 'Rodrigues',
    sex: 'Masculino',
    maritalStatus: 'Solteiro',
    creditLine: 'Boa',
    course: 'Medicina Veterinária',
    phone: '(99) 1111-1111',
    address: 'Rua N, 987',
  },
  {
    name: 'Isabela',
    cpf: '888.999.000-11',
    surname: 'Lima',
    sex: 'Feminino',
    maritalStatus: 'Casada',
    creditLine: 'Ótima',
    course: 'Engenharia Civil',
    phone: '(55) 1234-5678',
    address: 'Av. Q, 654',
  },
];
